### ISSUE TITLE
Vaccination data 

### ISSUE THREAD

**Issue by ninadicara** [DynamicGenetics/COVID-19-Community-Response#105]
I've looked into it now and the vaccination data is pulled from the same location as the COVID-19 case rate data is. 
This should mean we can reuse the same functions for collecting the dataset and will just need to write new ones to process the spreadsheet. 

I think we will want :
http://www2.nphs.wales.nhs.uk:8080/CommunitySurveillanceDocs.nsf/PublicPage?OpenPage&AutoFramed  
title = "COVID19 vaccination downloadable data"  
sheet = "HealthBoard_LocalAuthority"  
filters: Risk group = "Wales residents aged 18 years and older"   

There are columns for first and second dose so we might want to provide layers for both?

**Comment by leriomaggio** [comment]
@ninadicara  do you think we can now close this issue?

**Comment by ninadicara** [comment]
The only outstanding tasks are the Welsh version, and updating documentation. These can stay in this issue, or we can just group them together in #106 - WDYT?
