### ISSUE TITLE
borgLayers file needs manual reformat before use

### ISSUE THREAD

**Issue by CMorenoStokoe** [DynamicGenetics/COVID-19-Community-Response#4]
currently the borgLayers file needs reformat before use (i.e., removing all "* and *" strings). Valerio suggested we use a dataclass to output layers from the borg in the format we want. This stems from the issue that we are using objective javascript objects:

Desired format (obj JS):
`{
key : value,
"quotedKey" : value
}`

Current output format (JSON):
`{
"key" : value,
"quotedKey" : value
}`

**Comment by ninadicara** [comment]
Resolved in latest version :)
